<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Barun-Vaio" failures="1" tests="5" name="Personal Loan" time="0.335" errors="0" timestamp="2023-01-18T12:54:11 IST">
  <testcase classname="test.day1" name="Demo" time="0.053">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.day1.Demo(day1.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="test.day2" name="Ploan" time="0.006"/>
  <testcase classname="test.day4" name="LoginApiHomeLoan" time="0.013"/>
  <testcase classname="test.day4" name="MobileLoginHomeLoan" time="0.022"/>
  <testcase classname="test.day4" name="webLoginHomeLoan" time="0.033"/>
  <testcase classname="test.day1" name="SecondTest" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- Personal Loan -->
